apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: REST API for ${{ values.name }}
  tags:
    - rest
    - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: user:default/${{ values.owner }}
  system: backend
  definition:
    $text: ./openapi.yaml
