apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: tossapol1308/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - api
    - microservice
spec:
  type: service
  owner: user:default/${{ values.owner }}
  lifecycle: experimental
  system: backend